services:
  approach_planner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - ./config:/app/config
      - ./launch:/app/launch
      - ./src:/app/src
      - ./tests:/app/tests